// this is a local build file, used for debugging purposes only!
// YOU CANNOT CREATE DISTRIBUTIONS WITH IT (they are built with arc42-generator, see README)
//

plugins {
    id 'org.asciidoctor.jvm.convert' version '4.0.4'
}

apply plugin: 'java'

// what language are we building
// current choices: EN, DE
def LANGUAGE = 'DE'

// what version of the template are we building here
version = "1.0.0-${LANGUAGE}-LOCAL-BUILD"

// template version (revnumber, revdate, revremark), as passed by arc42-generator
def versionProps = new Properties()
file("${LANGUAGE}/version.properties").withReader('UTF-8') { versionProps.load(it) }

repositories {
    mavenCentral()
}


asciidoctor {
    baseDir file('./')
    baseDirFollowsSourceDir()

    sourceDir file("${LANGUAGE}")
    sources{ include 'req42-framework.adoc' }
   
    options = [
        includedir: "./${LANGUAGE}/",
        imagesdir: 'images'
    ]    
    
    outputDir = file( "build/${LANGUAGE}" )

    attributes versionProps

    resources {
        from("${LANGUAGE}") {
            include 'images/**'
        }
    }
}
