[[section-Stakeholder]]
== Stakeholder

[role="req42help"]
****
.Inhalt
Eine (priorisierte) Liste Ihrer Stakeholder, zusammen Angaben, wo diese Stakeholder bei der Analysearbeit helfen (oder hindern) können.

.Motivation
Stakeholder sind die wichtigsten Quellen für Anforderungen. Deshalb sollten Sie diese kennen und dokumentieren. Sie müssen wissen, wer davon Ihnen wobei helfen oder Sie in welcher Form behindern kann. Sie müssen wissen, wer welchen Einfluss hat – und bei unterschiedlichen Meinungen müssen Sie vermitteln oder entscheiden.
Ohne explizit identifizierte Stakeholder ist das alles schwierig.

.Notationen/Tools
* Tabellen oder Listen (einfache Form)
* Evtl. Stakeholder-Map (komplexere Form)

Nachfolgend haben wir als Beispiel eine einfache Stakeholder-Liste eingefügt. 
Die Reihenfolge "Rolle vor Person" ist bewusst gewählt. Diese Reihenfolge hat sich bewährt da Anforderungen normalerweise immer Bedarfe aus Sicht einer Rolle darstellen, die Person, welche die Rolle einnimmt, während des Projektes aber durchaus wechseln kann.
Sie können bei Bedarf auch gerne weitere Spalten hinzufügen (Kontaktdaten, …) – bedenken Sie aber den Aufwand für deren Pflege.

.Weiterführende Informationen

Siehe https://docs.arc42.org/section-3/[Kontextabgrenzung] in der online-Dokumentation (auf Englisch!).

****

[cols="1,1,2,2" options="header"]
|===
|Rolle |Person |Thema |Einfluss
| _<Rolle-1>_ | _<Person-1>_ | _<Thema-1>_ | _<Einfluss-1>_
| _<Rolle-2>_ | _<Person-2>_ | _<Thema-2>_ | _<Einfluss-2>_
|===
