[[section-teams]]
== Teams

ifdef::req42help[]
[role="req42help"]
****
.Content
This section can be omitted for small product developments with only one development team, since the team members are already listed in the previous section.  

For scaled large products, the organization chart of your teams should be here and an assignment to the topics (e.g. epics, features, ...) this team is responsible for.

.Motivation
If you have more than one team at your disposal, it goes without saying that you should have an overview of who works in which (sub-)team and how these teams are organized.
 
The focus should be on (sub-)teams being organized in such a way that they can deliver functions/features or partial products as independently as possible without having to constantly coordinate with everyone else. 

.Notations/Tools
Lists of teams (each with assigned people and assigned topics from the roadmap or from the product backlog (e.g., epics or features).

// .More Information
//
// https://docs.req42.de/section-xxx in the online documentation

****
endif::req42help[]

[cols="1,2,2" options="header"]
|===
|Team |Team Members |Feature  
| _<Team-1>_ |PO: _<Person-1>_ | _<Feature-A>_ 
|            | _<Team member-2>_|      
|            | _<Team member-3>_| 
|            |                  | 
| _<Team-2>_ |PO_<Person-2>_ | _<Feature-B>_ 
|            | _<Team member-2>_| 
|            |             |             |
|===